language: java

jdk:
  - openjdk8
  - openjdk11
  - oraclejdk11

os:
  - linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Override default install process on TravisCI
# Avoid default `gradlew assemble` execution. Be explicit about it on the `script` section.
# More info: https://github.com/travis-ci/travis-ci/issues/8667
install: true

# Build pipeline
# Compile before running the tests in order to easily check which task could be failing.
script:
  - ./gradlew assemble
  - ./gradlew check