image: java:11

options:
  max-time: 10

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew assemble --warning-mode all
          - bash ./gradlew check --warning-mode all
